# Customer Shopping Behavior Simulation - Personas Configuration
# Author: AI/Data Engineering Candidate
# Date: August 2025

personas:
  - name: "Young Professional"
    frequency: "alternate"
    preferred_time: ["6:00pm-8:00pm"]
    demographics:
      age_range: [25, 35]
      income_range: [40000, 80000]
      location_type: "urban"
      education: "graduate"
      family_status: "single"

    basket_profile:
      ready_meals:
        probability: 0.8
        quantity: [1, 2]
        price_range: [150, 400]

      coffee:
        probability: 0.9
        quantity: [1, 1]
        price_range: [300, 800]

      protein_bar:
        probability: 0.5
        quantity: [2, 4]
        price_range: [50, 120]

      fruit:
        probability: 0.3
        quantity: [1, 2]
        price_range: [80, 200]

      energy_drinks:
        probability: 0.4
        quantity: [1, 3]
        price_range: [60, 150]

  - name: "Family Shopper"
    frequency: "weekly"
    preferred_time: ["10:00am-12:00pm", "4:00pm-6:00pm"]
    demographics:
      age_range: [30, 50]
      income_range: [60000, 120000]
      location_type: "suburban"
      education: "graduate"
      family_status: "married_with_children"

    basket_profile:
      vegetables:
        probability: 0.9
        quantity: [3, 8]
        price_range: [200, 600]

      rice:
        probability: 0.8
        quantity: [1, 2]
        price_range: [800, 2000]

      dairy_products:
        probability: 0.85
        quantity: [2, 5]
        price_range: [50, 300]

      cooking_oil:
        probability: 0.6
        quantity: [1, 1]
        price_range: [150, 400]

      snacks:
        probability: 0.7
        quantity: [2, 5]
        price_range: [30, 150]

      cleaning_supplies:
        probability: 0.5
        quantity: [1, 3]
        price_range: [100, 350]

  - name: "Budget Conscious"
    frequency: "weekly"
    preferred_time: ["9:00am-11:00am", "2:00pm-4:00pm"]
    demographics:
      age_range: [22, 45]
      income_range: [25000, 50000]
      location_type: "mixed"
      education: "undergraduate"
      family_status: "mixed"

    basket_profile:
      basic_grains:
        probability: 0.9
        quantity: [2, 5]
        price_range: [50, 200]

      seasonal_vegetables:
        probability: 0.8
        quantity: [2, 6]
        price_range: [30, 150]

      local_fruits:
        probability: 0.6
        quantity: [1, 3]
        price_range: [40, 120]

      dairy_basic:
        probability: 0.7
        quantity: [1, 3]
        price_range: [25, 100]

      generic_brands:
        probability: 0.8
        quantity: [1, 4]
        price_range: [20, 80]

  - name: "Premium Shopper"
    frequency: "daily"
    preferred_time: ["11:00am-1:00pm", "7:00pm-9:00pm"]
    demographics:
      age_range: [35, 65]
      income_range: [100000, 300000]
      location_type: "urban"
      education: "postgraduate"
      family_status: "affluent"

    basket_profile:
      organic_produce:
        probability: 0.9
        quantity: [2, 6]
        price_range: [200, 800]

      imported_items:
        probability: 0.7
        quantity: [1, 3]
        price_range: [300, 1500]

      premium_dairy:
        probability: 0.8
        quantity: [1, 4]
        price_range: [150, 600]

      gourmet_foods:
        probability: 0.6
        quantity: [1, 2]
        price_range: [400, 2000]

      wine_beverages:
        probability: 0.4
        quantity: [1, 2]
        price_range: [800, 3000]

      health_supplements:
        probability: 0.5
        quantity: [1, 3]
        price_range: [500, 2500]

  - name: "Senior Citizen"
    frequency: "monthly"
    preferred_time: ["10:00am-12:00pm"]
    demographics:
      age_range: [60, 80]
      income_range: [30000, 70000]
      location_type: "mixed"
      education: "mixed"
      family_status: "retired"

    basket_profile:
      medicines:
        probability: 0.8
        quantity: [1, 3]
        price_range: [100, 500]

      basic_groceries:
        probability: 0.9
        quantity: [3, 8]
        price_range: [50, 300]

      traditional_foods:
        probability: 0.7
        quantity: [1, 4]
        price_range: [80, 400]

      health_foods:
        probability: 0.6
        quantity: [1, 3]
        price_range: [150, 600]

      household_essentials:
        probability: 0.5
        quantity: [1, 2]
        price_range: [100, 400]

# Market Configuration
market_config:
  festival_dates:
    - "2024-01-15" # Makar Sankranti
    - "2024-03-08" # Holi
    - "2024-08-19" # Raksha Bandhan
    - "2024-09-07" # Ganesh Chaturthi
    - "2024-10-12" # Dussehra
    - "2024-11-01" # Diwali
    - "2024-12-25" # Christmas

  seasonal_multipliers:
    festival: 1.5
    weekend: 1.2
    weekday: 1.0

  price_variations:
    festival_markup: [1.05, 1.15]
    discount_range: [0.9, 1.1]

# Simulation Configuration
simulation:
  default_days: 30
  customers_per_persona: 1000
  start_date: "2024-01-01"
  random_seed: 42
